// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnsubibxfbdvsbzaabij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuc3ViaWJ4ZmJkdnNiemFhYmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDQzNDYsImV4cCI6MjA2OTQyMDM0Nn0._-PcYNrqLNWJzmhXc4FGRQni0jTfHVV3ClmJdZOWoWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});